{
 "title": "AMIRIS",
 "time": { "from": "2019-01-10T21:48:00.000Z", "to": "2019-01-30T12:39:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "scenario",
    "query": "select schema_name\nfrom information_schema.schemata\nwhere schema_name like 'amiris_%'"
   }
  ]
 },
 "panels": [
  {
   "title": "Merit Order Forecaster",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"TimeStep\",$__interval),\n  \"AgentId\"::text as \"agent\",\n  avg(\"AwardedEnergyForecastInMWH\"*1e3) as \"AwardedEnergyForecastInMWH\",\n  avg(\"ElectricityPriceForecastInEURperMWH\") as \"ElectricityPriceForecastInEURperMWH\"\nFROM $scenario.meritorderforecaster\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1, \"agent\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "SystemOperatorTrader",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"TimeStep\",$__interval),\n  \"AgentId\"::text as \"agent\",\n  avg(\"AwardedEnergyInMWH\"*1e3) as \"AwardedEnergyInMWH\",\n  avg(\"OfferedEnergyInMWH\"*1e3) as \"OfferedEnergyInMWH\",\n  avg(\"ReceivedSupportInEUR\") as \"ReceivedSupportInEUR\",\n  avg(\"RefundedSupportInEUR\") as \"RefundedSupportInEUR\",\n  avg(\"ReceivedMarketRevenues\") as \"ReceivedMarketRevenuesInEUR\",\n  avg(\"TrueGenerationPotentialInMWH\"*1e3) as \"TrueGenerationPotentialInMWH\"\nFROM $scenario.SystemOperatorTrader\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1, \"agent\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "StorageTrader",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"TimeStep\",$__interval),\n  \"AgentId\"::text as \"agent\",\n  avg(\"AwardedEnergyInMWH\"*1e3) as \"AwardedEnergyInMWH\",\n  avg(\"OfferedEnergyInMWH\"*1e3) as \"OfferedEnergyInMWH\",\n  avg(\"OfferedChargePriceInEURperMWH\") as \"OfferedChargePriceInEURperMWH\",\n  avg(\"OfferedDischargePriceInEURperMWH\") as \"OfferedDischargePriceInEURperMWH\",\n  avg(\"AwardedChargeEnergyInMWH\"*1e3) as \"AwardedChargeEnergyInMWH\",\n  avg(\"AwardedDischargeEnergyInMWH\"*1e3) as \"AwardedDischargeEnergyInMWH\",\n  avg(\"StoredEnergyInMWH\"*1e3) as \"StoredEnergyInMWH\",\n  avg(\"VariableCostsInEUR\") as \"VariableCostsInEUR\",\n  avg(\"ReceivedMoneyInEUR\") as \"ReceivedMoneyInEUR\"\nFROM $scenario.StorageTrader\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1, \"agent\"\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "demandtrader",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"TimeStep\",$__interval),\n  \"AgentId\"::text as \"agent\",\n  avg(\"RequestedEnergyInMWH\")*1e3 as \"RequestedEnergyInMWH\",\n  avg(\"AwardedEnergyInMWH\")*1e3 as \"AwardedEnergyInMWH\"\nFROM $scenario.demandtrader\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1, \"agent\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "ConventionalPlantOperator",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"TimeStep\",$__interval),\n  \"AgentId\"::text as \"agent\",\n  avg(\"AwardedEnergyInMWH\"*1e3) as \"AwardedEnergyInMWH\",\n  avg(\"OfferedEnergyInMWH\"*1e3) as \"OfferedEnergyInMWH\",\n  avg(\"ReceivedMoneyInEUR\") as \"ReceivedMoneyInEUR\",\n  avg(\"VariableCostsInEUR\") as \"VariableCostsInEUR\"\nFROM $scenario.ConventionalPlantOperator\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1, \"agent\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "VariableRenewableOperator",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"TimeStep\",$__interval),\n  \"AgentId\"::text as \"agent\",\n  avg(\"AwardedEnergyInMWH\"*1e3) as \"AwardedEnergyInMWH\",\n  avg(\"OfferedEnergyInMWH\"*1e3) as \"OfferedEnergyInMWH\",\n  avg(\"ReceivedMoneyInEUR\") as \"ReceivedMoneyInEUR\",\n  avg(\"VariableCostsInEUR\") as \"VariableCostsInEUR\"\nFROM $scenario.VariableRenewableOperator\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1, \"agent\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "ConventionalPlantOperator_DispatchedEnergyInMWHperPlant",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"TimeStep\",$__interval),\n  \"AgentId\"::text as \"agent\",\n  \"ID\",\n  avg(\"DispatchedEnergyInMWHperPlant\"*1e3) as \"DispatchedEnergyInMWHperPlant\"\nFROM $scenario.ConventionalPlantOperator_DispatchedEnergyInMWHperPlant\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1, \"agent\", \"ID\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "ConventionalTrader",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"TimeStep\",$__interval),\n  \"AgentId\"::text as \"agent\",\n  avg(\"AwardedEnergyInMWH\"*1e3) as \"AwardedEnergyInMWH\",\n  avg(\"OfferedEnergyInMWH\"*1e3) as \"OfferedEnergyInMWH\"\nFROM $scenario.ConventionalTrader\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1, \"agent\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "ConventionalPlantOperator_VariableCostsInEURperPlant",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"TimeStep\",$__interval),\n  \"AgentId\"::text as \"agent\",\n  \"ID\",\n  avg(\"VariableCostsInEURperPlant\") as \"VariableCostsInEURperPlant\"\nFROM $scenario.ConventionalPlantOperator_VariableCostsInEURperPlant\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1, \"agent\", \"ID\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "ConventionalPlantOperator_ReceivedMoneyInEURperPlant",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"TimeStep\",$__interval),\n  \"AgentId\"::text as \"agent\",\n  \"ID\",\n  avg(\"ReceivedMoneyInEURperPlant\") as \"ReceivedMoneyInEURperPlant\"\nFROM $scenario.ConventionalPlantOperator_ReceivedMoneyInEURperPlant\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1, \"agent\", \"ID\"\nORDER BY 1"
    }
   ]
  }
 ]
}