{
 "title": "AMIRIS Comparison",
 "time": { "from": "2020-12-31T23:49:05.945Z", "to": "2021-01-01T21:05:40.528Z" },
 "templating": {
  "list": [
   {
    "name": "scenario",
    "query": "select schema_name\nfrom information_schema.schemata\nwhere schema_name like 'amiris_%'"
   },
   {
    "name": "scenario_pretty",
    "query": "Germany 2019, Austria 2019, Simple"
   }
  ]
 },
 "panels": [
  { "title": "Comparison View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "${scenario_pretty} Market Price",
   "type": "timeseries",
   "description": "Overview of market results for the chossen market",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "€/MWh" } },
   "targets": [
    {
     "rawSql": "SELECT\n  product_start AS \"time\",\n  avg(price) AS \"ASSUME Price\"\nFROM market_meta\nWHERE (\"simulation\" LIKE '$scenario') AND market_id = 'Market_1' AND $__timeFilter(product_start)\nGROUP BY market_id, simulation, product_start\nORDER BY 1;\n"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"TimeStep\",$__interval),\n  avg(\"ElectricityPriceInEURperMWH\") as \"AMIRIS Price\"\nFROM $scenario.DayAheadMarketSingleZone\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "${scenario_pretty} Demand",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(datetime,$__interval),\n  -avg(power) AS \"ASSUME Market Dispatch\"\nFROM market_dispatch\nWHERE\n  $__timeFilter(datetime) AND\n  LOWER(simulation) = '$scenario' AND\n  unit_id = 'demand_100_0'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"TimeStep\",$__interval),\n  avg(\"AwardedEnergyInMWH\") as \"AMIRIS Market Dispatch\"\nFROM $scenario.demandtrader\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "${scenario_pretty} Renewable Unitwise Dispatch",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "select \n$__timeGroupAlias(a.\"time\",$__interval),\navg(\"ASSUME Actual dispatch\") as \"ASSUME Actual dispatch\", \navg(\"AMIRIS Awarded Energy\") as \"AMIRIS Awarded Energy\",\navg(\"AMIRIS Awarded Energy\"- \"ASSUME Actual dispatch\") as \"Difference\", \na.\"agent\"\nfrom\n(SELECT\n  index as \"time\",\n  avg(power) AS \"ASSUME Actual dispatch\",\n  SUBSTRING(unit,27) as \"agent\"\nFROM unit_dispatch\nWHERE\n  $__timeFilter(index) AND\n  LOWER(simulation) = '$scenario' AND\n  unit like 'VariableRenewableOperator_%'\nGROUP BY 1, unit, power\nORDER BY 1) a\njoin (SELECT\n  \"TimeStep\" as \"time\",\n  \"AgentId\"::text as \"agent\",\n  avg(\"AwardedEnergyInMWH\") as \"AMIRIS Awarded Energy\"\n  --avg(\"OfferedEnergyInMWH\"*1e3) as \"OfferedEnergyInMWH\",\n  --avg(\"ReceivedMoneyInEUR\") as \"ReceivedMoneyInEUR\",\n  --avg(\"VariableCostsInEUR\") as \"VariableCostsInEUR\"\nFROM $scenario.VariableRenewableOperator\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1, \"agent\"\nORDER BY 1) b on a.agent=b.agent and a.time=b.time\n--where a.agent = '10'\nGROUP BY 1, a.\"agent\""
    }
   ]
  },
  {
   "title": "${scenario_pretty} Conventional",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "select \"ASSUME Actual dispatch\", \n\"AMIRIS Awarded Energy\",\n\"AMIRIS Awarded Energy\"- \"ASSUME Actual dispatch\" as \"Difference\", \na.\"time\", a.\"agent\"\nfrom\n(select\ntime,\nsum(\"ASSUME Actual dispatch\") as \"ASSUME Actual dispatch\",\nSUBSTRING(unit,27,1) as \"agent\"\nfrom\n(\nSELECT\n  $__timeGroupAlias(index,$__interval),\n  avg(power) AS \"ASSUME Actual dispatch\",\n  unit\nFROM unit_dispatch\nWHERE\n  $__timeFilter(index) AND\n  LOWER(simulation) = '$scenario' AND\n  unit like 'PredefinedPlantBuilder_200%'\nGROUP BY 1, unit, power\nORDER BY 1\n) q\ngroup by 1, agent) a\njoin (SELECT\n  $__timeGroupAlias(\"TimeStep\",$__interval),\n  substring(\"AgentId\"::text,3) as \"agent\",\n  avg(\"AwardedEnergyInMWH\") as \"AMIRIS Awarded Energy\"\n  --avg(\"OfferedEnergyInMWH\"*1e3) as \"OfferedEnergyInMWH\",\n  --avg(\"ReceivedMoneyInEUR\") as \"ReceivedMoneyInEUR\",\n  --avg(\"VariableCostsInEUR\") as \"VariableCostsInEUR\"\nFROM $scenario.ConventionalPlantOperator\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1, \"agent\"\nORDER BY 1) b on a.agent=b.agent and a.time=b.time"
    }
   ]
  },
  {
   "title": "Detail Views - Left ASSUME - Right AMIRIS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 }
  },
  {
   "title": "Market Summary ASSUME",
   "type": "timeseries",
   "description": "Overview of market results for the chossen market",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "repeat": "market",
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  product_start AS \"time\",\n  avg(demand_volume)*1e3 AS \"Demand volume\",\n  avg(price) AS \"Price\",\n  avg(supply_volume)*1e3 AS \"Supply volume\"\nFROM market_meta\nWHERE (\"simulation\" LIKE '$scenario') AND market_id = 'Market_1' AND $__timeFilter(product_start)\nGROUP BY market_id, simulation, product_start\nORDER BY 1;\n"
    }
   ]
  },
  {
   "title": "DayAheadMarketSingleZone AMIRIS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"TimeStep\",$__interval),\n  \"AgentId\"::text as \"agent\",\n  avg(\"ElectricityPriceInEURperMWH\") as \"ElectricityPriceInEURperMWH\",\n  avg(\"AwardedEnergyInMWH\"*1e3) as \"AwardedEnergyInMWH\",\n  avg(\"DispatchSystemCostInEUR\") as \"DispatchSystemCostInEUR\"\n  \nFROM $scenario.DayAheadMarketSingleZone\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1, \"agent\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Unitwise Dispatch",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(datetime,$__interval),\n  power AS \"Market dispatch\",\n  concat(unit_id, ' - ', market_id) as \"unit_id\"\nFROM market_dispatch\nWHERE\n  $__timeFilter(datetime) AND\n  LOWER(simulation) = '$scenario' AND\n  unit_id = 'demand_100_0'\nGROUP BY 1, unit_id, power, market_id\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(index,$__interval),\n  power AS \"Actual dispatch\",\n  unit\nFROM unit_dispatch\nWHERE\n  $__timeFilter(index) AND\n  LOWER(simulation) = '$scenario' AND\n  unit = 'demand_100_0'\nGROUP BY 1, unit, power\nORDER BY 1"
    }
   ]
  },
  {
   "title": "demandtrader",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"TimeStep\",$__interval),\n  \"AgentId\"::text as \"agent\",\n  -avg(\"RequestedEnergyInMWH\")*1e3 as \"RequestedEnergyInMWH\",\n  -avg(\"AwardedEnergyInMWH\")*1e3 as \"AwardedEnergyInMWH\"\nFROM $scenario.demandtrader\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1, \"agent\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Conventional Unitwise Dispatch",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(datetime,$__interval),\n  left(unit_id, 27) as unit,\n  avg(power) AS \"Market dispatch\"\n  \nFROM market_dispatch\nWHERE\n  $__timeFilter(datetime) AND\n  LOWER(simulation) = '$scenario' AND\n  unit_id like 'PredefinedPlantBuilder_200%'\nGROUP BY 1, unit_id, power\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(index,$__interval),\n  avg(power) AS \"Actual dispatch\",\n  left(unit, 27) as unit\nFROM unit_dispatch\nWHERE\n  $__timeFilter(index) AND\n  LOWER(simulation) = '$scenario' AND\n  unit like 'PredefinedPlantBuilder_200%'\nGROUP BY 1, unit, power\nORDER BY 1"
    }
   ]
  },
  {
   "title": "ConventionalPlantOperator",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"TimeStep\",$__interval),\n  \"AgentId\"::text as \"agent\",\n  avg(\"AwardedEnergyInMWH\"*1e3) as \"AwardedEnergyInMWH\",\n  avg(\"OfferedEnergyInMWH\"*1e3) as \"OfferedEnergyInMWH\",\n  avg(\"ReceivedMoneyInEUR\") as \"ReceivedMoneyInEUR\",\n  avg(\"VariableCostsInEUR\") as \"VariableCostsInEUR\"\nFROM $scenario.ConventionalPlantOperator\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1, \"agent\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Renewable Unitwise Dispatch",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(datetime,$__interval),\n  avg(power) AS \"Market dispatch\",\n  concat(unit_id, ' - ', market_id) as \"unit_id\"\nFROM market_dispatch\nWHERE\n  $__timeFilter(datetime) AND\n  LOWER(simulation) = '$scenario' AND\n  unit_id like 'VariableRenewableOperator_%'\nGROUP BY 1, unit_id, power, market_id\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(index,$__interval),\n  avg(power) AS \"Actual dispatch\",\n  unit\nFROM unit_dispatch\nWHERE\n  $__timeFilter(index) AND\n  LOWER(simulation) = '$scenario' AND\n  unit like 'VariableRenewableOperator_%'\nGROUP BY 1, unit, power\nORDER BY 1"
    }
   ]
  },
  {
   "title": "VariableRenewableOperator",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"TimeStep\",$__interval),\n  \"AgentId\"::text as \"agent\",\n  avg(\"AwardedEnergyInMWH\"*1e3) as \"AwardedEnergyInMWH\",\n  avg(\"OfferedEnergyInMWH\"*1e3) as \"OfferedEnergyInMWH\",\n  --avg(\"ReceivedMoneyInEUR\") as \"ReceivedMoneyInEUR\",\n  avg(\"VariableCostsInEUR\") as \"VariableCostsInEUR\"\nFROM $scenario.VariableRenewableOperator\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1, \"agent\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Merit Order Forecaster",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"TimeStep\",$__interval),\n  \"AgentId\"::text as \"agent\",\n  avg(\"AwardedEnergyForecastInMWH\"*1e3) as \"AwardedEnergyForecastInMWH\",\n  avg(\"ElectricityPriceForecastInEURperMWH\") as \"ElectricityPriceForecastInEURperMWH\"\nFROM $scenario.meritorderforecaster\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1, \"agent\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "StorageTrader",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"TimeStep\",$__interval),\n  \"AgentId\"::text as \"agent\",\n  avg(\"AwardedEnergyInMWH\"*1e3) as \"AwardedEnergyInMWH\",\n  avg(\"OfferedEnergyInMWH\"*1e3) as \"OfferedEnergyInMWH\",\n  avg(\"OfferedChargePriceInEURperMWH\") as \"OfferedChargePriceInEURperMWH\",\n  avg(\"OfferedDischargePriceInEURperMWH\") as \"OfferedDischargePriceInEURperMWH\",\n  avg(\"AwardedChargeEnergyInMWH\"*1e3) as \"AwardedChargeEnergyInMWH\",\n  avg(\"AwardedDischargeEnergyInMWH\"*1e3) as \"AwardedDischargeEnergyInMWH\",\n  avg(\"StoredEnergyInMWH\"*1e3) as \"StoredEnergyInMWH\",\n  avg(\"VariableCostsInEUR\") as \"VariableCostsInEUR\",\n  avg(\"ReceivedMoneyInEUR\") as \"ReceivedMoneyInEUR\"\nFROM $scenario.StorageTrader\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1, \"agent\"\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "ConventionalPlantOperator_DispatchedEnergyInMWHperPlant",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"TimeStep\",$__interval),\n  \"AgentId\"::text as \"agent\",\n  \"ID\",\n  avg(\"DispatchedEnergyInMWHperPlant\"*1e3) as \"DispatchedEnergyInMWHperPlant\"\nFROM $scenario.ConventionalPlantOperator_DispatchedEnergyInMWHperPlant\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1, \"agent\", \"ID\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "SystemOperatorTrader",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"TimeStep\",$__interval),\n  \"AgentId\"::text as \"agent\",\n  avg(\"AwardedEnergyInMWH\"*1e3) as \"AwardedEnergyInMWH\",\n  avg(\"OfferedEnergyInMWH\"*1e3) as \"OfferedEnergyInMWH\",\n  avg(\"ReceivedSupportInEUR\") as \"ReceivedSupportInEUR\",\n  avg(\"RefundedSupportInEUR\") as \"RefundedSupportInEUR\",\n  avg(\"ReceivedMarketRevenues\") as \"ReceivedMarketRevenuesInEUR\",\n  avg(\"TrueGenerationPotentialInMWH\"*1e3) as \"TrueGenerationPotentialInMWH\"\nFROM $scenario.SystemOperatorTrader\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1, \"agent\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "ConventionalPlantOperator_VariableCostsInEURperPlant",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"TimeStep\",$__interval),\n  \"AgentId\"::text as \"agent\",\n  \"ID\",\n  avg(\"VariableCostsInEURperPlant\") as \"VariableCostsInEURperPlant\"\nFROM $scenario.ConventionalPlantOperator_VariableCostsInEURperPlant\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1, \"agent\", \"ID\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "ConventionalTrader",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"TimeStep\",$__interval),\n  \"AgentId\"::text as \"agent\",\n  avg(\"AwardedEnergyInMWH\"*1e3) as \"AwardedEnergyInMWH\",\n  avg(\"OfferedEnergyInMWH\"*1e3) as \"OfferedEnergyInMWH\"\nFROM $scenario.ConventionalTrader\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1, \"agent\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "ConventionalPlantOperator_ReceivedMoneyInEURperPlant",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"TimeStep\",$__interval),\n  \"AgentId\"::text as \"agent\",\n  \"ID\",\n  avg(\"ReceivedMoneyInEURperPlant\") as \"ReceivedMoneyInEURperPlant\"\nFROM $scenario.ConventionalPlantOperator_ReceivedMoneyInEURperPlant\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1, \"agent\", \"ID\"\nORDER BY 1"
    }
   ]
  }
 ]
}